[gui]
font_size = 12

[models.vad]
model_path = "../ModelsAI/silero_vad.onnx"
threshold = 0.5
max_silence_chunks = 25
max_speech_duration_s = 10

[models.asr]
bootstrap_server = true
server_bin_path = "../llama/llama-server.exe"
model_path = "../ModelsAI/Qwen3-ASR-0.6B-Q8_0.gguf"
proj_path = "../ModelsAI/mmproj-Qwen3-ASR-0.6B-Q8_0.gguf"
server_url = "http://127.0.0.1:8080/v1/chat/completions"
threads = 2
n_gpu_layers = 99


[models.translate]
bootstrap_server = true
server_bin_path = "../llama/llama-server.exe"
model_path = "../ModelsAI/Qwen3-0.6B-abliterated.Q8_0.gguf"
server_url = "http://127.0.0.1:8081/v1/chat/completions"
threads = 2
n_gpu_layers = 99
temperature = 0.3
tgt_lang = "Chinese"